<?php

namespace AppBundle\Repository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($query)
    {
        return $this->createQueryBuilder('d')
            ->where('d.name LIKE :query')
            ->orWhere('d.serialNumber LIKE :query')
            ->orWhere('d.notes LIKE :query')
            ->setParameter('query', '%'.$query.'%')
            ->getQuery()
            ->getArrayResult();
    }
}
