<?php

namespace AppBundle\Repository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($query, $from, $to)
    {
        $q = $this->getEntityManager()->createQuery(
            'SELECT i FROM AppBundle:Invoice i WHERE (i.contractorName LIKE :query OR i.contractorVatid LIKE :query OR i.invoiceNumber LIKE :query) AND i.date BETWEEN :from AND :to'
        );
        $q->setParameter('query', '%'.$query.'%');
        $q->setParameter('from', $from);
        $q->setParameter('to', $to);
        return $q->getArrayResult();
    }
}
