<?php

namespace AppBundle\Repository;

/**
 * LicenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenseRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($query)
    {
        return $this->createQueryBuilder('l')
            ->where('l.name LIKE :query')
            ->orWhere('l.serialNumber LIKE :query')
            ->orWhere('l.notes LIKE :query')
            ->setParameter('query', '%'.$query.'%')
            ->getQuery()
            ->getArrayResult();
    }
}
