<?php

namespace AppBundle\Repository;

/**
 * LicenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenseRepository extends \Doctrine\ORM\EntityRepository
{
}
