<?php

namespace AppBundle\Repository;

/**
 * PresenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($query, $from, $to)
    {
        $q = $this->getEntityManager()->createQuery(
            'SELECT p, u FROM AppBundle:Presence p JOIN p.user u WHERE u.username LIKE :query AND p.date BETWEEN :from AND :to'
        );
        $q->setParameter('query', '%'.$query.'%');
        $q->setParameter('from', $from);
        $q->setParameter('to', $to);;
        return $q->getArrayResult();
    }
}
